

###############################################################################################################################
## Some comments on the modifications by Richie Wyss to allow pre-ordering specified by user and patience keyword.
## 		- Including preOrdering was as simple as modifying a single loop in the select_terms function.
## 		- Modifying the code to include the patience keyword was more difficult and required modifying the
## 			cv function.
##		- Also, when patience is specified, preOrdering needs to be set to TRUE. Setting the patience
##			parameter only makes sense with preOrdered variables
##		- When preOrdering is TRUE, the code was also modified to run the CV function first
##			This allows the program to first identify how many variables to include in the full ctmle analysis



# Aug 1, 2012
# set PEN= FALSE as default.
# July 3, 2012
# add start = 0 for fitting epsilon -- don't know if it will make a difference
# April 17, 2012
# Add the earlystopFactor arg for stopping once built past the point that a canddiate will be chosen
#
# March 16, 2012
# Added optional argument V for number of cross-validation folds.
# default value is 5, same as the old behavior.

# Collaborative Targeted Maximum Likelihood Estimation (ctmle)
# Susan Gruber      (sgruber@berkeley.edu)
# Mark van der Laan (laan@berkeley.edu)
# September 15, 2010

# ATE parameter
# ------Updates-------
# Dec 7, 2011
# removed projection onto A in stage 1
# also changed cv pen from var(IC) to var(Dstar)
# updated Feb 15, 2011
# ICg calculation fixed

# The DSA and SuperLearner packages are strongly recommended in order to
# obtain reliable results.
#
# SuperLearner is available at http://www.stat.berkeley.edu/users/ecpolley/SL/
# DSA: http://www.stat.berkeley.edu/users/laan/Software/
# These packages depend on
#   modelUtils:  http://www.stat.berkeley.edu/users/laan/Software/
#   nnls:        http://cran.r-project.org/web/packages/nnls/index.html
#   quadprog:    http://cran.r-project.org/web/packages/quadprog/index.html

#----------- Description -----------
# This R source code implements C-TMLE, originally
# described in Gruber S., van der Laan J., "An Application of Collaborative
# Targeted Maximum Likelihood Estimation in Causal Inference and Genomics,"
# The International Journal of Biostatistics,(6)1, 2010.
#
# The parameter of interest estimated by this program is the additive
# effect of a binary point treatment, A, on an outcome, Y, adjusting
# for a set of potential confounders, W (binary and/or continuous).
# Psi = E(Y(1)-Y(0)) = E_W(EY | A=1,W) - E(Y|A=0,W), based on observing n
# i.i.d. observations on (W,A,Y).  Missing data are not allowed
#
# Stage 1: Super Learner, a data-adaptive prediction algorithm, is used to obtain
# an initial estimate for the regression of Y on A and W, denoted as Q(A,W).
# A cross-validated initial estimate
# is suggested, but is not the default because it is more time consuming.
# If Super Learner is not available there are three options
#	1. user-supplied externally estimated values, passed in through argument Q,
# 	   an nx3 matrix with columns Q(A,W)=E(Y|A,W), Q(1,W)=E(Y|A=1,W), Q(0,W)=E(Y|A=0,W)
#   2. user-supplied regression formula suitable for a call to glm
#   3. an initial estimate is obtained by main terms regression of Y on A and W
#
# Stage 2: Candidate models for g(A,W)= (P(A=1|W) are generated by forward selection.
# Each of these is mapped into a separate clever covariate h(g_n), used to fluctuate
# updated estimates of Q, thereby creating candidate tmle estimators.
#
# The ctmle estimate is the best of these candidates, selected with 5-fold penalized
# likelihood-based cross validation.
